# Generated by Django 2.1.5 on 2020-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom_1', models.CharField(max_length=50)),
                ('Symptom_2', models.CharField(max_length=50)),
                ('Symptom_3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
