# Generated by Django 2.1.5 on 2020-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.CharField(max_length=50)),
                ('value_2', models.CharField(max_length=50)),
                ('value_3', models.CharField(max_length=50)),
                ('value_4', models.CharField(max_length=50)),
                ('value_5', models.CharField(max_length=50)),
                ('value_6', models.CharField(max_length=50)),
            ],
        ),
    ]
