# Generated by Django 2.1.5 on 2020-06-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='Symptom_3',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
