# Generated by Django 2.1.5 on 2020-06-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disease_symptom_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='Symptom_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
