# Generated by Django 2.1.5 on 2021-03-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('appointment_date', models.DateTimeField()),
                ('appointment_status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Completed', 'Completed')], max_length=20)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorInfo')),
            ],
        ),
    ]
