# Generated by Django 2.1.5 on 2021-07-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '__first__'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('appointment_date', models.DateTimeField()),
                ('appointment_status', models.IntegerField(default=0)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorInfo')),
            ],
        ),
        migrations.CreateModel(
            name='BookedAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.AppointmentDetails')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile')),
            ],
        ),
    ]
