# Generated by Django 2.1.5 on 2021-03-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='appointment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='appointment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.AppointmentDetails'),
        ),
        migrations.AddField(
            model_name='bookedappointment',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Profile'),
        ),
    ]
