# Generated by Django 2.1.5 on 2021-03-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(upload_to='images/'),
        ),
    ]
