# Generated by Django 2.1.5 on 2020-10-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease1',
            old_name='doctor_name',
            new_name='doctor',
        ),
    ]
