# Generated by Django 2.1.5 on 2020-06-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200606_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='email',
        ),
    ]
