# Generated by Django 2.1.5 on 2020-10-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0002_auto_20201019_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease1',
            name='doctor',
        ),
        migrations.AddField(
            model_name='disease1',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorInfo'),
        ),
    ]
