# Generated by Django 2.1.5 on 2020-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patientinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
