# Generated by Django 2.1.5 on 2020-10-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='profile',
            new_name='uploaded_by',
        ),
    ]
