# Generated by Django 2.1.5 on 2020-07-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20200713_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease1',
            old_name='doctor_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='disease1',
            old_name='disease_name',
            new_name='name',
        ),
    ]
