# Generated by Django 2.1.5 on 2020-06-07 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_auto_20200607_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientInfo',
            new_name='Profile',
        ),
    ]
