# Generated by Django 2.1.5 on 2020-07-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20200713_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoPredictDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('predicted_disease', models.CharField(max_length=50)),
            ],
        ),
    ]
