# Generated by Django 2.1.5 on 2020-06-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20200608_1824'),
        ('patient', '0008_auto_20200608_1112'),
    ]

    operations = [
    ]
