# Generated by Django 2.1.5 on 2020-07-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20200713_1243'),
        ('patient', '0005_image'),
    ]

    operations = [
    ]
