# Generated by Django 2.1.5 on 2021-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='education_year',
            field=models.DateTimeField(),
        ),
    ]
