# Generated by Django 2.1.5 on 2020-11-07 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
