# Generated by Django 2.1.5 on 2020-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='category',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
