# Generated by Django 2.1.5 on 2020-07-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='category',
        ),
    ]
