# Generated by Django 2.1.5 on 2020-11-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20201106_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='hospital',
        ),
    ]
