# Generated by Django 2.1.5 on 2020-10-22 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20201021_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
