# Generated by Django 2.1.5 on 2020-10-22 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20201021_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='education_year',
            field=models.DateTimeField(),
        ),
    ]
