# Generated by Django 2.1.5 on 2020-10-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20201022_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='doctorinfo',
            name='education_year',
        ),
    ]
