# Generated by Django 2.1.5 on 2020-10-22 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20201022_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
