# Generated by Django 2.1.5 on 2020-10-22 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_doctorinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='education_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
