# Generated by Django 2.1.5 on 2020-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_doctorinfo_education_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='doc_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
